import type {
  Control,
  DataSource,
  Location,
  Organization,
  Signal,
  User,
  ValueSummary,
} from "../types";

export const ORG: Organization = {
  id: "org_northstar",
  name: "Northstar Hospitality Group",
  locations: 12,
  countries: 9,
  demo: true,
};

export const LOCATIONS: Location[] = [
  {
    id: "loc_ber",
    name: "Berlin Mitte",
    city: "Berlin",
    country: "DE",
    openSignals: 3,
    valueOnRadr: 19_600,
    verifiedValue: 7_420,
    lastSync: "2 min ago",
  },
  {
    id: "loc_ber_kreuz",
    name: "Berlin Kreuzberg",
    city: "Berlin",
    country: "DE",
    openSignals: 2,
    valueOnRadr: 15_200,
    verifiedValue: 5_600,
    lastSync: "4 min ago",
  },
  {
    id: "loc_nyc",
    name: "New York Flatiron",
    city: "New York",
    country: "US",
    openSignals: 4,
    valueOnRadr: 31_200,
    verifiedValue: 12_800,
    lastSync: "3 min ago",
  },
  {
    id: "loc_nyc_wvill",
    name: "New York West Village",
    city: "New York",
    country: "US",
    openSignals: 2,
    valueOnRadr: 24_600,
    verifiedValue: 9_900,
    lastSync: "5 min ago",
  },
  {
    id: "loc_sf",
    name: "San Francisco Hayes",
    city: "San Francisco",
    country: "US",
    openSignals: 3,
    valueOnRadr: 22_400,
    verifiedValue: 8_700,
    lastSync: "6 min ago",
  },
  {
    id: "loc_tyo",
    name: "Tokyo Shibuya",
    city: "Tokyo",
    country: "JP",
    openSignals: 3,
    valueOnRadr: 27_800,
    verifiedValue: 10_400,
    lastSync: "3 min ago",
  },
  {
    id: "loc_sin",
    name: "Singapore Marina",
    city: "Singapore",
    country: "SG",
    openSignals: 2,
    valueOnRadr: 21_100,
    verifiedValue: 8_200,
    lastSync: "7 min ago",
  },
  {
    id: "loc_dxb",
    name: "Dubai Marina",
    city: "Dubai",
    country: "AE",
    openSignals: 2,
    valueOnRadr: 18_900,
    verifiedValue: 6_800,
    lastSync: "8 min ago",
  },
  {
    id: "loc_syd",
    name: "Sydney Surry Hills",
    city: "Sydney",
    country: "AU",
    openSignals: 2,
    valueOnRadr: 16_400,
    verifiedValue: 6_100,
    lastSync: "9 min ago",
  },
  {
    id: "loc_ams",
    name: "Amsterdam Centraal",
    city: "Amsterdam",
    country: "NL",
    openSignals: 4,
    valueOnRadr: 26_400,
    verifiedValue: 11_200,
    lastSync: "5 min ago",
  },
  {
    id: "loc_ams_canal",
    name: "Canal House Amsterdam",
    city: "Amsterdam",
    country: "NL",
    openSignals: 2,
    valueOnRadr: 18_400,
    verifiedValue: 6_200,
    lastSync: "3 min ago",
  },
  {
    id: "loc_lis_residences",
    name: "Lisbon Residences",
    city: "Lisbon",
    country: "PT",
    openSignals: 2,
    valueOnRadr: 14_200,
    verifiedValue: 5_100,
    lastSync: "4 min ago",
  },
  {
    id: "loc_lon",
    name: "London Soho",
    city: "London",
    country: "UK",
    openSignals: 5,
    valueOnRadr: 28_400,
    verifiedValue: 11_200,
    lastSync: "4 min ago",
  },
  {
    id: "loc_par",
    name: "Paris Marais",
    city: "Paris",
    country: "FR",
    openSignals: 4,
    valueOnRadr: 24_100,
    verifiedValue: 9_840,
    lastSync: "6 min ago",
  },
];

export const USERS: User[] = [
  {
    id: "u_maria",
    name: "Maria Rossi",
    role: "Procurement Manager",
    email: "maria@northstar.demo",
    scope: "Group procurement",
    openAssignments: 4,
  },
  {
    id: "u_james",
    name: "James Okonkwo",
    role: "Finance",
    email: "james@northstar.demo",
    scope: "Group finance",
    openAssignments: 3,
  },
  {
    id: "u_lena",
    name: "Lena Berg",
    role: "Regional Manager",
    email: "lena@northstar.demo",
    scope: "Global operations",
    openAssignments: 6,
  },
  {
    id: "u_tom",
    name: "Tom Hale",
    role: "GM",
    email: "tom@northstar.demo",
    scope: "New York Flatiron",
    openAssignments: 2,
  },
  {
    id: "u_sara",
    name: "Sara Nguyen",
    role: "Operations",
    email: "sara@northstar.demo",
    scope: "Labor · APAC + US",
    openAssignments: 5,
  },
];

export const VALUE: ValueSummary = {
  identified: 684_000,
  actioned: 214_000,
  resolved: 186_400,
  recoveredPreventedCaptured: 214_000,
  verified: 58_900,
  byArea: {
    buy: 22_400,
    labor: 11_800,
    sell: 17_100,
    recover: 7_600,
  },
  byLocation: [
    { locationId: "loc_nyc", value: 14_200 },
    { locationId: "loc_tyo", value: 11_400 },
    { locationId: "loc_ber", value: 12_100 },
    { locationId: "loc_lon", value: 9_800 },
    { locationId: "loc_sin", value: 6_200 },
    { locationId: "loc_sf", value: 5_200 },
  ],
  recovered: 58_900,
  prevented: 126_400,
  captured: 28_700,
};

export const METER = {
  valueOnRadr: 176_740,
  annualized: 172_460,
  recoverable: 4_280,
  openSignals: 10,
  highImpact: 4,
  waitingOnAction: 3,
  locations: 12,
} as const;

/** Territory intelligence: demo figures must reconcile within each page */
export const TERRITORY = {
  buy: {
    primary: 48_200,
    label: "Open exposure",
    meta: [
      { label: "open signals", value: 6 },
      { label: "high impact", value: 2 },
      { label: "suppliers flagged", value: 11 },
    ],
    breakdown: [
      { label: "Supplier pricing", value: 18_620, pct: 39 },
      { label: "Contract adherence", value: 12_400, pct: 26 },
      { label: "Invoice accuracy", value: 8_960, pct: 19 },
      { label: "Waste / yield", value: 8_220, pct: 17 },
    ],
  },
  labor: {
    primary: 28_460,
    label: "Avoidable labor exposure",
    meta: [
      { label: "open signals", value: 4 },
      { label: "locations tonight", value: 3 },
      { label: "agency dependency", value: "18%" },
    ],
    breakdown: [
      { label: "Demand vs schedule", value: 12_840, pct: 45 },
      { label: "Overtime", value: 6_420, pct: 23 },
      { label: "Agency dependency", value: 5_200, pct: 18 },
      { label: "Productivity drag", value: 4_000, pct: 14 },
    ],
  },
  sell: {
    primary: 34_200,
    label: "Missed upside",
    meta: [
      { label: "open signals", value: 4 },
      { label: "high impact", value: 2 },
      { label: "locations affected", value: 6 },
    ],
    breakdown: [
      { label: "Menu pricing", value: 14_200, pct: 42 },
      { label: "Commissions", value: 6_840, pct: 20 },
      { label: "Promotions", value: 7_360, pct: 22 },
      { label: "Channel mix", value: 5_800, pct: 17 },
    ],
  },
  recover: {
    primary: 18_620,
    label: "Recoverable now",
    meta: [
      { label: "open cases", value: 5 },
      { label: "high impact", value: 2 },
      { label: "suppliers", value: 8 },
    ],
    breakdown: [
      { label: "Credits", value: 4_280, pct: 23 },
      { label: "Rebates", value: 3_600, pct: 19 },
      { label: "Refunds", value: 5_240, pct: 28 },
      { label: "Settlements / disputes", value: 5_500, pct: 30 },
    ],
  },
} as const;

export const OPERATING_MODEL = {
  locations: 12,
  suppliers: 126,
  items: 4_820,
  employees: 342,
  invoices: 12_482,
  credits: 1_204,
  contracts: 4_820,
} as const;

export const SOURCES: DataSource[] = [
  { id: "pms", name: "PMS", status: "CONNECTED", lastSync: "1 min ago" },
  { id: "pos", name: "POS", status: "CONNECTED", lastSync: "2 min ago" },
  {
    id: "proc",
    name: "Procurement",
    status: "CONNECTED",
    lastSync: "3 min ago",
  },
  {
    id: "wf",
    name: "Workforce",
    status: "SYNCING",
    lastSync: "Now",
  },
  {
    id: "acc",
    name: "Accounting",
    status: "CONNECTED",
    lastSync: "5 min ago",
  },
  {
    id: "pay",
    name: "Payments",
    status: "NEEDS_ATTENTION",
    lastSync: "2 days ago",
  },
  {
    id: "del",
    name: "Delivery",
    status: "CONNECTED",
    lastSync: "8 min ago",
  },
  { id: "files", name: "Files", status: "CONNECTED", lastSync: "12 min ago" },
];

export const CONTROLS: Control[] = [
  {
    id: "ctrl_001",
    name: "Supplier invoice price must match active contract",
    description: "Invoice price must not exceed the active contract price.",
    sourceSignalId: "sig_001",
    scope: "All locations · FreshCo → All suppliers",
    condition: "actual_price <= contract_price",
    action: "Create signal",
    status: "ACTIVE",
    createdAt: "12 days ago",
    lastRunAt: "2 min ago",
    preventedCount: 14,
    protectedValue: 26_840,
    owner: "Procurement",
    runHistory: ["Passed", "Passed", "Flagged", "Passed", "Passed", "Passed"],
  },
  {
    id: "ctrl_002",
    name: "Labor schedule must stay within demand threshold",
    description: "Scheduled headcount vs forecast demand.",
    sourceSignalId: "sig_003",
    scope: "All locations",
    condition: "scheduled <= demand_target * 1.1",
    action: "Create signal",
    status: "ACTIVE",
    createdAt: "21 days ago",
    lastRunAt: "5 min ago",
    preventedCount: 9,
    protectedValue: 18_420,
    owner: "Operations",
    runHistory: ["Passed", "Flagged", "Passed", "Passed"],
  },
  {
    id: "ctrl_003",
    name: "Credit due date must not pass without receipt",
    description: "Expected credits tracked to receipt.",
    sourceSignalId: "sig_002",
    scope: "Group finance",
    condition: "credit_received_by_due_date",
    action: "Create signal",
    status: "ACTIVE",
    createdAt: "8 days ago",
    lastRunAt: "11 min ago",
    preventedCount: 6,
    protectedValue: 12_600,
    owner: "Finance",
    runHistory: ["Passed", "Passed", "Passed", "Flagged"],
  },
  {
    id: "ctrl_004",
    name: "Delivery commission must match agreement",
    description: "Platform commission vs commercial terms.",
    sourceSignalId: "sig_007",
    scope: "Delivery channels",
    condition: "commission_rate <= agreed_rate",
    action: "Create signal",
    status: "ACTIVE",
    createdAt: "30 days ago",
    lastRunAt: "18 min ago",
    preventedCount: 4,
    protectedValue: 8_940,
    owner: "Revenue",
    runHistory: ["Passed", "Passed", "Passed"],
  },
];

export const SIGNALS: Signal[] = [
  {
    id: "sig_001",
    area: "buy",
    type: "Supplier pricing mismatch",
    title: "Supplier pricing mismatch",
    description:
      "You paid more than agreed. Invoice price exceeds the active contract price for this supplier and item.",
    subject: "Avocado Hass 18ct · FreshCo",
    locationId: "loc_ams",
    impact: 18_620,
    impactLabel: "€18,620",
    impactType: "exposure",
    period: " / year",
    expected: { label: "Contract", value: "€31.20" },
    actual: { label: "Invoice", value: "€34.80" },
    delta: "€3.60 / case",
    volume: "5,172 cases / year",
    why: "Invoice price exceeds the active contract price for this supplier and item.",
    evidence: [
      {
        id: "ev1",
        name: "Contract · FreshCo 2026.pdf",
        kind: "pdf",
        role: "Expected source",
      },
      {
        id: "ev2",
        name: "Invoice #48291.pdf",
        kind: "pdf",
        role: "Actual source",
      },
      {
        id: "ev3",
        name: "Purchase history.csv",
        kind: "csv",
        role: "Volume source",
      },
      {
        id: "ev4",
        name: "Supplier statement.pdf",
        kind: "pdf",
        role: "Supporting",
      },
    ],
    ownerId: "u_maria",
    ownerName: "Maria Rossi",
    status: "IN_REVIEW",
    priority: 1,
    detectedAt: "12 min ago",
    recommendation: "Review supplier charge.",
    activity: [
      {
        id: "a1",
        actor: "RADR",
        body: "Detected mismatch",
        at: "12 min ago",
      },
      {
        id: "a2",
        actor: "Maria",
        body: "Assigned to Procurement",
        at: "8 min ago",
      },
      {
        id: "a3",
        actor: "Maria",
        body: "Supplier contacted",
        at: "3 min ago",
      },
    ],
  },
  {
    id: "sig_002",
    area: "recover",
    type: "Credit never received",
    title: "Supplier credit never received",
    description: "This credit never arrived.",
    subject: "Credit note · FreshCo correction",
    locationId: "loc_ber",
    impact: 4_280,
    impactLabel: "€4,280",
    impactType: "recoverable",
    period: "",
    expected: { label: "Credit due", value: "€4,280" },
    actual: { label: "Received", value: "€0" },
    delta: "€4,280",
    why: "Expected credit from supplier correction was never received.",
    evidence: [
      {
        id: "ev5",
        name: "Credit note expected.pdf",
        kind: "pdf",
        role: "Expected source",
      },
      {
        id: "ev6",
        name: "Supplier statement.pdf",
        kind: "pdf",
        role: "Actual source",
      },
    ],
    ownerId: "u_james",
    ownerName: "James Okonkwo",
    status: "RECOVERABLE",
    priority: 2,
    detectedAt: "28 min ago",
    recommendation: "Open credit case.",
    activity: [
      {
        id: "a4",
        actor: "RADR",
        body: "Detected missing credit",
        at: "28 min ago",
      },
    ],
  },
  {
    id: "sig_003",
    area: "labor",
    type: "Schedule above demand",
    title: "Scheduled above demand",
    description: "You scheduled above demand.",
    subject: "Thursday dinner service",
    locationId: "loc_lon",
    impact: 840,
    impactLabel: "€840",
    impactType: "exposure",
    period: " tonight",
    expected: { label: "Needed", value: "11" },
    actual: { label: "Scheduled", value: "14" },
    delta: "3 staff",
    why: "Scheduled headcount exceeds demand forecast for Thursday dinner.",
    evidence: [
      {
        id: "ev7",
        name: "Demand forecast.csv",
        kind: "csv",
        role: "Expected source",
      },
      {
        id: "ev8",
        name: "Roster · Thursday.pdf",
        kind: "pdf",
        role: "Actual source",
      },
    ],
    ownerId: "u_sara",
    ownerName: "Sara Nguyen",
    status: "ACTIONABLE",
    priority: 3,
    detectedAt: "41 min ago",
    recommendation: "Review tonight's schedule.",
    activity: [
      {
        id: "a5",
        actor: "RADR",
        body: "Detected overstaffing",
        at: "41 min ago",
      },
    ],
  },
  {
    id: "sig_004",
    area: "sell",
    type: "Menu item underpriced",
    title: "Menu item underpriced",
    description: "You're selling out too cheaply.",
    subject: "Truffle Rigatoni",
    locationId: "loc_ams",
    impact: 14_200,
    impactLabel: "€14,200",
    impactType: "missed_upside",
    period: " / year",
    expected: { label: "Expected", value: "€27.50" },
    actual: { label: "Current", value: "€24.00" },
    delta: "€3.50 / item",
    why: "Ingredient cost increased 11% while menu price remained unchanged.",
    evidence: [
      {
        id: "ev9",
        name: "Menu engineering.xlsx",
        kind: "xlsx",
        role: "Expected source",
      },
      {
        id: "ev10",
        name: "POS mix · 30d.csv",
        kind: "csv",
        role: "Actual source",
      },
    ],
    ownerId: "u_lena",
    ownerName: "Lena Berg",
    status: "MISSED_UPSIDE",
    priority: 4,
    detectedAt: "18 min ago",
    recommendation: "Review price recommendation.",
    activity: [
      {
        id: "a6",
        actor: "RADR",
        body: "Detected underpricing",
        at: "18 min ago",
      },
    ],
  },
  {
    id: "sig_005",
    area: "buy",
    type: "Duplicate invoice",
    title: "Duplicate invoice",
    description: "Same invoice appears twice in the period.",
    subject: "Invoice #48110 · ProduceCo",
    locationId: "loc_ams",
    impact: 2_140,
    impactLabel: "€2,140",
    impactType: "recoverable",
    period: "",
    expected: { label: "Unique invoices", value: "1" },
    actual: { label: "Found", value: "2" },
    delta: "1 duplicate",
    why: "Identical invoice number and amount posted twice.",
    evidence: [
      {
        id: "ev11",
        name: "Invoice #48110.pdf",
        kind: "pdf",
        role: "Primary",
      },
      {
        id: "ev12",
        name: "Invoice #48110-b.pdf",
        kind: "pdf",
        role: "Duplicate",
      },
    ],
    ownerId: "u_james",
    ownerName: "James Okonkwo",
    status: "REVIEW",
    priority: 5,
    detectedAt: "2 hr ago",
    recommendation: "Block duplicate payment.",
    activity: [
      {
        id: "a7",
        actor: "RADR",
        body: "Detected duplicate",
        at: "2 hr ago",
      },
    ],
  },
  {
    id: "sig_006",
    area: "labor",
    type: "Overtime developing",
    title: "Overtime developing",
    description: "Projected overtime above plan for tonight.",
    subject: "Dinner service · floor",
    locationId: "loc_sf",
    impact: 216,
    impactLabel: "€216",
    impactType: "exposure",
    period: " tonight",
    expected: { label: "Planned OT", value: "€0" },
    actual: { label: "Projected", value: "€216" },
    delta: "€216",
    why: "Projected overtime exceeds plan for the dinner service.",
    evidence: [
      {
        id: "ev13",
        name: "Shift plan.csv",
        kind: "csv",
        role: "Expected source",
      },
    ],
    ownerId: "u_sara",
    ownerName: "Sara Nguyen",
    status: "NEW",
    priority: 6,
    detectedAt: "3 hr ago",
    recommendation: "Review roster before service.",
    activity: [
      {
        id: "a8",
        actor: "RADR",
        body: "Detected overtime risk",
        at: "3 hr ago",
      },
    ],
  },
  {
    id: "sig_007",
    area: "sell",
    type: "Delivery commission increase",
    title: "Delivery commission increase",
    description: "Platform commission above agreement.",
    subject: "Delivery · commission",
    locationId: "loc_tyo",
    impact: 6_840,
    impactLabel: "€6,840",
    impactType: "exposure",
    period: " / year",
    expected: { label: "Agreed", value: "22%" },
    actual: { label: "Charged", value: "28%" },
    delta: "6 pts",
    why: "Delivery platform commission exceeds commercial agreement.",
    evidence: [
      {
        id: "ev14",
        name: "Delivery agreement.pdf",
        kind: "pdf",
        role: "Expected source",
      },
      {
        id: "ev15",
        name: "Payout week 32.csv",
        kind: "csv",
        role: "Actual source",
      },
    ],
    ownerId: "u_lena",
    ownerName: "Lena Berg",
    status: "ASSIGNED",
    priority: 7,
    detectedAt: "5 hr ago",
    recommendation: "Review commission charge.",
    activity: [
      {
        id: "a9",
        actor: "RADR",
        body: "Detected commission delta",
        at: "5 hr ago",
      },
    ],
  },
  {
    id: "sig_009",
    area: "sell",
    type: "Promotion destroying contribution",
    title: "Promotion destroying contribution",
    description: "Promo margin below floor on high-volume SKU.",
    subject: "Happy Hour",
    locationId: "loc_par",
    impact: 7_360,
    impactLabel: "€7,360",
    impactType: "exposure",
    period: " / year",
    expected: { label: "Contribution floor", value: "55%" },
    actual: { label: "Promo contribution", value: "31%" },
    delta: "24 pts",
    why: "Promotion discount exceeds contribution floor on a high-velocity item.",
    evidence: [
      {
        id: "ev17",
        name: "Promo calendar.xlsx",
        kind: "xlsx",
        role: "Expected source",
      },
      {
        id: "ev18",
        name: "POS promo mix.csv",
        kind: "csv",
        role: "Actual source",
      },
    ],
    ownerId: "u_lena",
    ownerName: "Lena Berg",
    status: "MISSED_UPSIDE",
    priority: 5,
    detectedAt: "18 min ago",
    recommendation: "Tighten promo rules or retire offer.",
    activity: [
      {
        id: "a11",
        actor: "RADR",
        body: "Detected promo contribution breach",
        at: "18 min ago",
      },
    ],
  },
  {
    id: "sig_011",
    area: "sell",
    type: "Channel mix opportunity",
    title: "Channel mix opportunity",
    description: "High-margin dine-in capacity unused vs delivery mix.",
    subject: "Dine-in vs delivery mix",
    locationId: "loc_lon",
    impact: 5_800,
    impactLabel: "€5,800",
    impactType: "missed_upside",
    period: " / year",
    expected: { label: "Target dine-in", value: "62%" },
    actual: { label: "Current dine-in", value: "48%" },
    delta: "14 pts",
    why: "Delivery share rose while higher-contribution dine-in capacity remained open.",
    evidence: [
      {
        id: "ev19",
        name: "Channel mix 90d.csv",
        kind: "csv",
        role: "Actual source",
      },
    ],
    ownerId: "u_tom",
    ownerName: "Tom Hale",
    status: "NEW",
    priority: 9,
    detectedAt: "6 hr ago",
    recommendation: "Shift promo spend toward dine-in capture.",
    activity: [
      {
        id: "a12",
        actor: "RADR",
        body: "Detected channel mix delta",
        at: "6 hr ago",
      },
    ],
  },
  {
    id: "sig_008",
    area: "recover",
    type: "Rebate missing",
    title: "Volume rebate missing",
    description: "Expected quarterly rebate not received.",
    subject: "Q2 volume rebate · ProduceCo",
    locationId: "loc_lon",
    impact: 3_600,
    impactLabel: "€3,600",
    impactType: "recoverable",
    period: "",
    expected: { label: "Rebate due", value: "€3,600" },
    actual: { label: "Received", value: "€0" },
    delta: "€3,600",
    why: "Volume threshold met; rebate not posted.",
    evidence: [
      {
        id: "ev16",
        name: "Rebate terms.pdf",
        kind: "pdf",
        role: "Expected source",
      },
    ],
    ownerId: "u_maria",
    ownerName: "Maria Rossi",
    status: "RECOVERABLE",
    priority: 8,
    detectedAt: "1 day ago",
    recommendation: "Request rebate remittance.",
    activity: [
      {
        id: "a10",
        actor: "RADR",
        body: "Detected missing rebate",
        at: "1 day ago",
      },
    ],
  },
  {
    id: "sig_010",
    area: "recover",
    type: "Delivery payout discrepancy",
    title: "Delivery payout discrepancy",
    description:
      "Platform payout is below expected settlement after refunds, discounts and contracted fees.",
    subject: "Platform payout · Week 32",
    locationId: "loc_ber",
    impact: 332,
    impactLabel: "€332",
    impactType: "recoverable",
    period: "",
    expected: { label: "Expected payout", value: "€11,570" },
    actual: { label: "Received", value: "€11,238" },
    delta: "€332",
    volume: "1,000 orders",
    why: "Gross sales minus refunds, discounts and contracted fees should settle at €11,570.",
    evidence: [
      {
        id: "ev_pay1",
        name: "Platform payout statement · W32.pdf",
        kind: "pdf",
        role: "Actual source",
      },
      {
        id: "ev_pay2",
        name: "Delivery contract · fee schedule.pdf",
        kind: "pdf",
        role: "Expected source",
      },
      {
        id: "ev_pay3",
        name: "Order ledger · W32.csv",
        kind: "csv",
        role: "Volume source",
      },
    ],
    ownerId: "u_james",
    ownerName: "James Okonkwo",
    status: "ACTIONABLE",
    priority: 1,
    detectedAt: "18 min ago",
    recommendation: "Open payout claim for €283 recoverable.",
    activity: [
      {
        id: "a_pay1",
        actor: "RADR",
        body: "Detected €332 payout delta",
        at: "18 min ago",
      },
      {
        id: "a_pay2",
        actor: "RADR",
        body: "Explained: €199 commission · €84 reimbursement · €49 valid adjustment",
        at: "12 min ago",
      },
      {
        id: "a_pay3",
        actor: "RADR",
        body: "€283 marked actionable",
        at: "9 min ago",
      },
    ],
  },
];

export function formatEuro(n: number) {
  return `€${Math.max(0, Math.round(n)).toLocaleString("en-IE")}`;
}

export function locationById(id: string) {
  return LOCATIONS.find((l) => l.id === id);
}

export function signalById(id: string) {
  return SIGNALS.find((s) => s.id === id);
}

export function controlById(id: string) {
  return CONTROLS.find((c) => c.id === id);
}

export function areaLabel(area: string) {
  return area.toUpperCase();
}

export function statusLabel(s: string) {
  return s.replace(/_/g, " ");
}
