import type { MemoryStory } from "./types";

export const MEMORY_CHAIN: MemoryStory[] = [
  {
    id: "comparable",
    n: "12",
    label: "Comparable nights",
    kicker: "12 comparable Friday services",
    title: "Friday peak capacity",
    tried: "Feature-swap-first vs rush-order across matching Fridays",
    observed: "Kitchen minutes recovered when signature mix de-emphasized",
    verified: "3 nights Verified contribution protected vs seat-now baseline",
    next: "Default Wait-12 + feature path before adding labor",
    euro: 620,
    grade: "Expected",
  },
  {
    id: "patterns",
    n: "5",
    label: "Patterns",
    kicker: "5 patterns",
    title: "Kitchen constraint before seats",
    tried: "Occupancy-led seating vs kitchen-led hold",
    observed: "Occupancy alone misleads when kitchen ≥90%",
    verified: "Pattern held across 5 compressed inbound windows",
    next: "Surface kitchen % on Needs-you before floor density",
  },
  {
    id: "interventions",
    n: "4",
    label: "What we tried",
    kicker: "4 interventions",
    title: "Hold · throttle · feature · protect",
    tried: "Prepared action set reused — not a new task list each Friday",
    observed: "Operators approved Wait-12 faster when Futures showed €",
    verified: "Adoption up · false alerts down on matching services",
    next: "Keep Approve → Confirm prepare; never fake SoR writes",
  },
  {
    id: "verified",
    n: "3",
    label: "Verified",
    kicker: "3 verified improvements",
    title: "Contribution protected at peak",
    tried: "Wait-12 + delivery throttle on comparable peaks",
    observed: "Second turns held · comps did not spike",
    verified: "€ matched against seat-now baselines on ledger",
    next: "Promote path into Playbook v3 default",
    euro: 2830,
    grade: "Verified",
  },
  {
    id: "playbook",
    n: "v3",
    label: "Next time",
    kicker: "Playbook v3",
    title: "Friday peak capacity protocol",
    tried: "Feature-swap-first outperformed rush-order",
    observed: "12 comparable services · kitchen cool-down after hold",
    verified: "3 verified improvements · Trace on tuna shortfall sealed",
    next: "Tonight: open Brief → FOH hold + Chef cold-station",
    euro: 620,
    grade: "Expected",
  },
];
