import { DECISION } from "./ids";
import type { ModulePin, RoleId, Wedge } from "./types";

export const MODULES: ModulePin[] = [
  {
    id: "mod_peak",
    category: "SELL",
    decisionId: DECISION.peak.id,
    displayId: DECISION.peak.displayId,
    title: "WAIT 12 MINUTES",
    euro: 620,
    euroLabel: "Expected contribution",
    clock: "Decide by 18:53 · ~11m",
    grade: "Expected",
    because: "Kitchen 92% · seat-now burns 9 second turns",
    blurb: "38 inbound + delivery +31% — hold walk-ins, throttle delivery.",
    href: "/app/lab/control-center?seed=service",
    seed: "service",
  },
  {
    id: "mod_menu",
    category: "SELL",
    decisionId: DECISION.menuPeak.id,
    displayId: DECISION.menuPeak.displayId,
    title: "DE-EMPHASIZE PEAK WINDOW",
    euro: 610,
    euroLabel: "Expected protected",
    clock: "Tonight · 19:00–20:30",
    grade: "Expected",
    because: "Signature mix burns cold-station minutes at peak",
    blurb: "BUY × LABOR × SELL — feature swap before rush-order.",
    href: "/app/lab/decisions",
    seed: "service",
  },
  {
    id: "mod_hotel",
    category: "SELL",
    decisionId: DECISION.hotelOrphan.id,
    displayId: DECISION.hotelOrphan.displayId,
    title: "RELEASE ORPHAN NIGHTS",
    euro: 640,
    euroLabel: "Expected contribution",
    clock: "Tonight · before 20:00",
    grade: "Expected",
    because: "2 unsold nights after cancellation cluster",
    blurb: "Release / reprice on direct — do not dump remaining to OTA.",
    href: "/app/lab/control-center?seed=hotel",
    seed: "hotel",
  },
  {
    id: "mod_labor",
    category: "LABOR",
    decisionId: DECISION.labor.id,
    displayId: DECISION.labor.displayId,
    title: "HOLD LABOR PLAN",
    euro: 410,
    euroLabel: "Expected protected",
    clock: "Tonight service",
    grade: "Expected",
    because: "Headcount in plan — risk is kitchen mix, not roster",
    blurb: "Do not add labor; protect contribution via Wait-12 path.",
    href: "/app/lab/decisions",
    seed: "service",
  },
  {
    id: "mod_supplier",
    category: "RECOVER",
    decisionId: DECISION.supplier.id,
    displayId: DECISION.supplier.displayId,
    title: "DISPUTE AP CREDIT",
    euro: 273,
    euroLabel: "Expected recoverable",
    clock: "11 days · 28 Sep",
    grade: "Expected",
    because: "INV-88421 above contract — CM draft pending Trace",
    blurb: "Contract €6.80/L · invoice €7.45/L · 420 L.",
    href: "/app/lab/control-center?seed=recover",
    seed: "recover",
  },
  {
    id: "mod_buy_oil",
    category: "BUY",
    decisionId: DECISION.supplier.id,
    displayId: DECISION.supplier.displayId,
    title: "HOLD ABOVE-CONTRACT PO",
    euro: 273,
    euroLabel: "Exposure · invoice",
    clock: "This week",
    grade: "Expected",
    because: "Next PO fires the same variance if yield unchecked",
    blurb: "Hold PO until dispute + yield path clear.",
    href: "/app/lab/control-center?seed=recover",
    seed: "recover",
  },
  {
    id: "mod_tuna_v",
    category: "VALUE",
    decisionId: DECISION.tuna.id,
    displayId: DECISION.tuna.displayId,
    title: "TUNA SHORTFALL · VERIFIED",
    euro: 1590,
    euroLabel: "Verified protected",
    clock: "Verified · 12 Sep",
    grade: "Verified",
    because: "POS close + stock adjustment matched on ledger",
    blurb: "Trace sealed — book-matchable Verified Value.",
    href: "/app/lab/value?band=verified",
  },
  {
    id: "mod_value_ladder",
    category: "VALUE",
    decisionId: DECISION.peak.id,
    displayId: "LEDGER",
    title: "VERIFIED VALUE LADDER",
    euro: 2830,
    euroLabel: "Verified total",
    clock: "Since last check",
    grade: "Verified",
    because: "Identified → Expected → Observed → Attributed → Verified",
    blurb: "Portfolio ladder — connection across Decisions, not a lone total.",
    href: "/app/lab/value?band=verified",
  },
  {
    id: "mod_memory",
    category: "MEMORY",
    decisionId: DECISION.playbook.id,
    displayId: "PLAYBOOK",
    title: "FRIDAY PEAK CAPACITY",
    euro: 0,
    euroLabel: "12 comparable services",
    clock: "Playbook v3",
    grade: "Verified",
    because: "Feature-swap-first beat rush-order on 3 verified nights",
    blurb: "What we tried → observed → verified → next Friday.",
    href: "/app/lab/memory?scope=playbook",
  },
];

export const CATALOG_ORDER: Wedge[] = ["SELL", "LABOR", "BUY", "RECOVER", "VALUE", "MEMORY"];

export const ROLE_PRESETS: Record<RoleId, string[]> = {
  gm: ["mod_peak", "mod_labor", "mod_menu", "mod_memory"],
  cfo: ["mod_supplier", "mod_buy_oil", "mod_tuna_v", "mod_value_ladder"],
  clevel: ["mod_value_ladder", "mod_peak", "mod_supplier", "mod_memory"],
};

export function pinsFor(ids: string[]): ModulePin[] {
  return ids
    .map((id) => MODULES.find((m) => m.id === id))
    .filter((m): m is ModulePin => Boolean(m));
}
