import type { LabRole, RoleLens } from "./types";

export const ROLE_LENSES: Record<LabRole, RoleLens> = {
  gm: {
    role: "gm",
    label: "GM",
    title: "Control Center",
    subtitle: "Ops tonight · who’s coming · what to hold",
    demoPath: "GM night-of · graph → decision → brief",
    showBrief: true,
    defaultBrief: "foh",
    showFloor: true,
    showWinLoss: false,
    showThemes: false,
    catalogEmphasis: ["SELL", "LABOR"],
    pulseMode: "ops",
  },
  cfo: {
    role: "cfo",
    label: "CFO",
    title: "Control Center",
    subtitle: "Money in / out · Recover + Buy · Verified ladder",
    demoPath: "CFO Monday · in/out/forecast → Recover",
    showBrief: true,
    defaultBrief: "cfo",
    showFloor: false,
    showWinLoss: true,
    showThemes: false,
    catalogEmphasis: ["RECOVER", "BUY", "VALUE"],
    pulseMode: "pnl",
  },
  clevel: {
    role: "clevel",
    label: "C-level",
    title: "Control Center",
    subtitle: "Pulse summary · three money themes · Verified",
    demoPath: "C-level · themes, not the floor map",
    showBrief: false,
    defaultBrief: "gm",
    showFloor: false,
    showWinLoss: true,
    showThemes: true,
    catalogEmphasis: ["VALUE", "SELL", "RECOVER"],
    pulseMode: "summary",
  },
};
