import type {
  BriefPacket,
  CatalogModule,
  HealthSource,
  LabDecision,
  LabSeed,
  LabWorld,
  MemoryStory,
  PulsePoint,
  ServiceBrief,
  ShiftPulse,
  ValueEntry,
} from "./types";

function series(
  rows: Array<[string, string, number, number, number, number]>,
): PulsePoint[] {
  return rows.map(([t, label, inn, out, net, forecast]) => ({
    t,
    label,
    in: inn,
    out,
    net,
    forecast,
  }));
}

const SERVICE_SHIFT = series([
  ["17:00", "17:00", 180, 40, 140, 160],
  ["17:15", "17:15", 320, 70, 250, 280],
  ["17:30", "17:30", 540, 120, 420, 460],
  ["17:45", "17:45", 820, 190, 630, 690],
  ["18:00", "18:00", 1280, 310, 970, 1040],
  ["18:15", "18:15", 1960, 560, 1400, 1520],
  ["18:30", "18:30", 2860, 980, 1880, 2060],
  ["18:42", "now", 4120, 1280, 1840, 2280],
  ["19:00", "19:00", 0, 0, 0, 2680],
  ["19:30", "19:30", 0, 0, 0, 3120],
  ["20:00", "20:00", 0, 0, 0, 3480],
  ["21:00", "21:00", 0, 0, 0, 3720],
  ["22:00", "22:00", 0, 0, 0, 3860],
  ["23:00", "close", 0, 0, 0, 3940],
]);

const SERVICE_24H = series([
  ["18:00y", "−24h", 3980, 980, 3010, 3100],
  ["20:00y", "20:00", 6120, 1420, 3680, 3720],
  ["22:00y", "22:00", 7040, 1680, 3920, 3880],
  ["00:00", "00:00", 7180, 1710, 3990, 3940],
  ["08:00", "08:00", 240, 40, 180, 160],
  ["12:00", "12:00", 1860, 420, 980, 1040],
  ["15:00", "15:00", 2640, 610, 1320, 1480],
  ["17:00", "17:00", 3180, 740, 1540, 1760],
  ["18:42", "now", 4120, 1280, 1840, 2280],
]);

const HOTEL_SHIFT = series([
  ["14:00", "14:00", 1860, 420, 1440, 1520],
  ["14:30", "14:30", 2740, 680, 2060, 2180],
  ["15:00", "15:00", 3920, 980, 2940, 3120],
  ["15:30", "15:30", 5180, 1420, 3760, 4080],
  ["16:00", "16:00", 6840, 1960, 4880, 5240],
  ["16:10", "now", 7460, 2380, 5080, 5620],
  ["17:00", "17:00", 0, 0, 0, 6180],
  ["18:00", "18:00", 0, 0, 0, 6720],
  ["20:00", "20:00", 0, 0, 0, 7140],
  ["22:00", "close", 0, 0, 0, 7380],
]);

const HOTEL_24H = series([
  ["16:00y", "−24h", 6920, 1880, 5040, 5180],
  ["20:00y", "20:00", 8120, 2140, 5980, 6040],
  ["00:00", "00:00", 8460, 2210, 6250, 6280],
  ["08:00", "08:00", 1240, 180, 980, 1040],
  ["12:00", "12:00", 2860, 640, 2120, 2280],
  ["14:00", "14:00", 4180, 980, 3200, 3460],
  ["16:10", "now", 7460, 2380, 5080, 5620],
]);

const RECOVER_SHIFT = series([
  ["D-13", "D-13", 3420, 810, 2610, 2680],
  ["D-11", "D-11", 3560, 840, 2720, 2710],
  ["D-9", "D-9", 3480, 910, 2570, 2740],
  ["D-7", "D-7", 3610, 880, 2730, 2760],
  ["D-5", "D-5", 3390, 1020, 2370, 2780],
  ["D-3", "D-3", 3520, 940, 2580, 2800],
  ["D-1", "D-1", 3470, 890, 2580, 2810],
  ["today", "today", 3440, 1160, 2280, 2820],
]);

const RECOVER_24H = series([
  ["W1", "W1", 24100, 5820, 18280, 18600],
  ["W2", "W2", 23840, 6140, 17700, 18720],
  ["now", "14d", 48200, 12400, 35800, 37400],
]);

const SERVICE_PULSE: ShiftPulse = {
  industry: "restaurant",
  title: "Shift Pulse",
  windowLabel: "Tonight · 18:00–now",
  headline: "Covers hold · delivery tax rising · Wait-12 still open",
  net: {
    euro: 1840,
    grade: "Expected",
    because: "Expected until close — not Verified. Pace vs forecast is the story.",
  },
  forecastClose: {
    euro: 3940,
    grade: "Expected",
    because: "Expected close if Wait-12 holds second turns and delivery throttle sticks.",
  },
  trackingNote: "Behind forecast by €440 at 18:42 — delivery take + cancel cluster, not covers.",
  metrics: [
    {
      id: "covers",
      label: "Covers in",
      euro: 4120,
      because: "56 covers seated · second turns still ahead",
      tone: "in",
    },
    {
      id: "delivery",
      label: "Delivery out",
      euro: 890,
      because: "Delivery +31% vs plan · channel take compressing margin",
      tone: "out",
    },
    {
      id: "cancels",
      label: "Cancels / walk-aways",
      euro: 210,
      because: "2 walk-aways after 18:30 hold · recoverable if Wait-12 holds",
      tone: "out",
    },
    {
      id: "comps",
      label: "Comps / voids",
      euro: 180,
      because: "1 VIP comp pending · kitchen delay risk",
      tone: "out",
    },
    {
      id: "net",
      label: "Net contribution",
      euro: 1840,
      because: "Expected until close — not Verified",
      grade: "Expected",
      tone: "net",
    },
  ],
  series: SERVICE_SHIFT,
  series24h: SERVICE_24H,
  turbulence: [
    {
      id: "t-del",
      t: "18:15",
      label: "Delivery spike",
      because: "Channel mix leaking contribution vs dine-in · throttle is the lever",
      decisionId: "d-1911",
      displayId: "D-1911",
      euro: 180,
      grade: "Expected",
      kind: "delivery",
    },
    {
      id: "t-can",
      t: "18:30",
      label: "Cancel cluster",
      because: "2 walk-aways after hold · Wait-12 still protects turns",
      decisionId: "d-1911",
      displayId: "D-1911",
      euro: 210,
      grade: "Expected",
      kind: "cancel",
    },
    {
      id: "t-kit",
      t: "18:42",
      label: "Kitchen 92%",
      because: "38 inbound + delivery pressure → Wait-12 protects turns",
      decisionId: "d-1911",
      displayId: "D-1911",
      euro: 620,
      grade: "Expected",
      kind: "kitchen",
    },
  ],
};

const HOTEL_PULSE: ShiftPulse = {
  industry: "hotel",
  title: "Shift Pulse",
  windowLabel: "Arrivals day · 14:00–now",
  headline: "OTA mix heavy · 3 orphan nights · no-show deposits uncharged",
  net: {
    euro: 5080,
    grade: "Expected",
    because: "Room contribution so far — Expected until night audit, not Verified.",
  },
  forecastClose: {
    euro: 7380,
    grade: "Expected",
    because: "Expected house close if OTA hold sticks and no-show path executes.",
  },
  trackingNote: "Behind pickup by €540 — OTA tax + two late cancels, not occupancy.",
  metrics: [
    {
      id: "arrivals",
      label: "Arrivals in",
      euro: 4120,
      because: "28 arrivals seated · 6 still inbound before 18:00",
      tone: "in",
    },
    {
      id: "rooms",
      label: "Room revenue",
      euro: 2680,
      because: "BAR vs OTA mix · occupancy 81% vs 86% pickup",
      tone: "in",
    },
    {
      id: "upsell",
      label: "Upgrades / upsells",
      euro: 660,
      because: "3 room upgrades + late checkout accepted",
      tone: "in",
    },
    {
      id: "cancels",
      label: "Cancels / no-shows",
      euro: 890,
      because: "2 late cancels + 1 no-show · deposit authorized, not charged",
      tone: "out",
    },
    {
      id: "refunds",
      label: "Refunds",
      euro: 240,
      because: "1 early departure refund pending night audit",
      tone: "out",
    },
    {
      id: "ota",
      label: "OTA distribution tax",
      euro: 1250,
      because: "Booking.com / Expedia take on remaining allotment",
      tone: "out",
    },
    {
      id: "net",
      label: "Net contribution",
      euro: 5080,
      because: "Expected until night audit — not Verified",
      grade: "Expected",
      tone: "net",
    },
  ],
  series: HOTEL_SHIFT,
  series24h: HOTEL_24H,
  turbulence: [
    {
      id: "t-ota",
      t: "15:30",
      label: "OTA spike",
      because: "Last-room allotment leaking BAR · hold channel before 17:00",
      decisionId: "d-8801",
      displayId: "D-8801",
      euro: 410,
      grade: "Expected",
      kind: "channel",
    },
    {
      id: "t-orph",
      t: "16:00",
      label: "Orphan-night risk",
      because: "3 disconnected nights after a midweek cancel cluster",
      decisionId: "d-8801",
      displayId: "D-8801",
      euro: 360,
      grade: "Expected",
      kind: "hold",
    },
    {
      id: "t-noshow",
      t: "16:10",
      label: "No-show uncharged",
      because: "Deposit authorized · charge not executed — Recover path",
      decisionId: "d-8802",
      displayId: "D-8802",
      euro: 280,
      grade: "Expected",
      kind: "recover",
    },
  ],
};

const RECOVER_PULSE: ShiftPulse = {
  industry: "restaurant",
  title: "Shift Pulse",
  windowLabel: "Rolling 14d · money out",
  headline: "AP variance open · credit memo not posted",
  net: {
    euro: -273,
    grade: "Expected",
    because: "INV-88421 above contract — Expected until credit memo is applied.",
  },
  forecastClose: {
    euro: 2830,
    grade: "Verified",
    because: "Already banked on tuna shortfall + prior closes · Trace sealed.",
    lineage: "POS close + stock adjustment matched · Trace D-1842",
  },
  trackingNote: "Books are clean on Verified €2,830. The open leak is AP — not the till.",
  metrics: [
    {
      id: "rev",
      label: "Revenue in",
      euro: 48200,
      because: "POS close · last 14 nights",
      tone: "in",
    },
    {
      id: "ap",
      label: "AP out",
      euro: 12400,
      because: "Invoices matched · one variance open",
      tone: "out",
    },
    {
      id: "var",
      label: "Invoice variance",
      euro: 273,
      because: "INV-88421 above contract €6.80/L · 420 L",
      grade: "Expected",
      tone: "out",
    },
    {
      id: "prot",
      label: "Verified protected",
      euro: 2830,
      because: "Ledger-matched · Trace sealed",
      grade: "Verified",
      tone: "net",
    },
  ],
  series: RECOVER_SHIFT,
  series24h: RECOVER_24H,
  turbulence: [
    {
      id: "t-ap",
      t: "D-5",
      label: "AP variance",
      because: "Contract vs invoice · dispute before next PO",
      decisionId: "d-4102",
      displayId: "D-4102",
      euro: 273,
      grade: "Expected",
      kind: "recover",
    },
    {
      id: "t-po",
      t: "today",
      label: "Above-contract PO",
      because: "Hold PO until yield + CM path clear",
      decisionId: "d-4102",
      displayId: "D-4102",
      euro: 273,
      grade: "Expected",
      kind: "hold",
    },
  ],
};

export const DECISIONS: LabDecision[] = [
  {
    id: "d-1911",
    displayId: "D-1911",
    title: "WAIT 12 MINUTES",
    sub: "Hold 2 walk-ins · throttle 25m · feature high €/min · resume 18:54",
    wedge: "SELL",
    euro: 620,
    grade: "Expected",
    because: "Kitchen 92% · seat-now burns 9 second turns",
    clock: "Decide by 18:53 · ~11m",
    decideBy: "18:53",
    seed: "service",
    status: "needs_you",
    autopilot: "stage",
    policy: {
      canAuto: ["Throttle delivery intake 25m"],
      alwaysAsk: ["Post to Instagram", "Seat walk-ins against hold"],
      memoryLine: "Seen 12 similar Fridays · auto-stage allowed.",
      interruptReason: "High € tonight · first confirm this pattern this week.",
    },
    futures: [
      { id: "seat_now", title: "Seat now", euro: 0, note: "Kitchen →97% · turns slip" },
      {
        id: "wait_12",
        title: "Wait 12 min",
        euro: 620,
        note: "Hold walk-ins · throttle delivery",
        recommended: true,
        recover: true,
      },
      { id: "hard_stop", title: "Kill delivery", euro: 180, note: "Protects kitchen · over-corrects" },
    ],
    recommendedFuture: "wait_12",
    actuators: [
      {
        system: "FLOOR",
        title: "Hold next walk-in table",
        detail: "Resume 18:54 — demo prepare, not written to SoR",
        policy: "ask",
      },
      {
        system: "DELIVERY",
        title: "Throttle 25 minutes",
        detail: "Policy allows auto after similar Fridays — still staged here",
        policy: "auto",
      },
      {
        system: "MENU",
        title: "Feature faster high-€/min dish",
        detail: "Peak window only · demo actuator",
        policy: "demo",
      },
    ],
  },
  {
    id: "d-1920",
    displayId: "D-1920",
    title: "HOLD LABOR PLAN",
    sub: "Headcount in plan — risk is kitchen mix, not roster",
    wedge: "LABOR",
    euro: 410,
    grade: "Expected",
    because: "Headcount OK — risk is kitchen mix, not roster",
    clock: "Tonight service",
    seed: "service",
    status: "handling",
    autopilot: "auto",
    policy: {
      canAuto: ["Hold roster · do not add agency"],
      alwaysAsk: ["Call extra bartender", "Post labor change to payroll SoR"],
      memoryLine: "Seen 8 matching Friday peaks · auto-hold within policy.",
      interruptReason: null,
    },
    futures: [
      { id: "add", title: "Add 1 FOH", euro: -180, note: "Pays for a mix problem" },
      { id: "hold", title: "Hold plan", euro: 410, note: "Protect via Wait-12 path", recommended: true },
    ],
    recommendedFuture: "hold",
    actuators: [
      {
        system: "LABOR",
        title: "Keep published roster",
        detail: "Auto within policy — no SoR write",
        policy: "auto",
      },
    ],
  },
  {
    id: "d-7110",
    displayId: "D-7110",
    title: "DE-EMPHASIZE PEAK WINDOW",
    sub: "Signature mix burns cold-station minutes at peak",
    wedge: "SELL",
    euro: 610,
    grade: "Expected",
    because: "Signature mix burns cold-station minutes at peak",
    clock: "Tonight · 19:00–20:30",
    seed: "service",
    status: "needs_you",
    autopilot: "suggest",
    policy: {
      canAuto: ["Feature-swap prompt on KDS"],
      alwaysAsk: ["Reprint menu", "Post feature to Instagram"],
      memoryLine: "Feature-swap-first beat rush-order on 3 verified nights.",
      interruptReason: "Menu change is first-time this LTO — Needs you.",
    },
    futures: [
      { id: "rush", title: "Rush-order", euro: 0, note: "Kitchen minutes burn" },
      {
        id: "swap",
        title: "Feature swap",
        euro: 610,
        note: "De-emphasize signature 19:00–20:30",
        recommended: true,
      },
    ],
    recommendedFuture: "swap",
    actuators: [
      {
        system: "MENU",
        title: "De-emphasize Tuna Tataki 19:00–20:30",
        detail: "Demo / policy — not a live menu write",
        policy: "demo",
      },
    ],
    demo: true,
  },
  {
    id: "d-7501",
    displayId: "D-7501",
    title: "CATEGORY REBALANCE",
    sub: "This week · before next beverage feature",
    wedge: "SELL",
    euro: 168,
    grade: "Expected",
    because: "This week · before next beverage feature",
    clock: "This week · before next beverage feature",
    seed: "service",
    status: "needs_you",
    autopilot: "suggest",
    policy: {
      canAuto: [],
      alwaysAsk: ["Change featured cocktail", "Print new menu"],
      memoryLine: "No comparable Verified week yet — Suggest only.",
      interruptReason: "First-time pattern.",
    },
    futures: [
      { id: "hold", title: "Hold mix", euro: 0, note: "Leaves leak in by-the-glass" },
      { id: "rebalance", title: "Rebalance", euro: 168, note: "Feature higher €/min pour", recommended: true },
    ],
    recommendedFuture: "rebalance",
    actuators: [
      {
        system: "BAR",
        title: "Feature higher contribution pour",
        detail: "Demo recommendation",
        policy: "demo",
      },
    ],
    demo: true,
  },
  {
    id: "d-4102",
    displayId: "D-4102",
    title: "DISPUTE AP CREDIT",
    sub: "Dispute INV-88421 · hold next above-contract PO · check yield · no reprice",
    wedge: "RECOVER",
    euro: 273,
    grade: "Expected",
    because: "INV-88421 above contract — CM draft pending",
    clock: "28 Sep · 11 days",
    decideBy: "28 Sep",
    seed: "recover",
    status: "needs_you",
    autopilot: "suggest",
    policy: {
      canAuto: [],
      alwaysAsk: ["Dispute AP / draft credit request", "Short-pay invoice", "Write to AP SoR"],
      memoryLine: "Always-ask: AP dispute is human-in-loop. Never silent remittance.",
      interruptReason: "High-trust money movement · always Needs you.",
    },
    futures: [
      { id: "seat_now", title: "Pay as invoiced", euro: 0, note: "Variance compounds" },
      {
        id: "wait_12",
        title: "Dispute + yield",
        euro: 273,
        note: "AP credit path",
        recommended: true,
        recover: true,
      },
      { id: "hard_stop", title: "Reprice menu", euro: null, euroLabel: "—", note: "Does not resolve source" },
    ],
    recommendedFuture: "wait_12",
    actuators: [
      {
        system: "AP",
        title: "Draft credit request",
        detail: "INV-88421 · CM-DRAFT — confirm prepare, do not write SoR",
        policy: "ask",
      },
      {
        system: "Purchasing",
        title: "Hold next above-contract PO",
        detail: "Prepared · not written back",
        policy: "ask",
      },
      {
        system: "Kitchen",
        title: "Investigate usage / yield",
        detail: "+4% usage separate from price effect",
        policy: "demo",
      },
    ],
    lineage: "€ Verified only when credit_memo.applied matches invoice/payment.",
  },
  {
    id: "d-8801",
    displayId: "D-8801",
    title: "HOLD OTA ALLOTMENT",
    sub: "Close last-room OTA · protect BAR · stitch 3 orphan nights",
    wedge: "SELL",
    euro: 410,
    grade: "Expected",
    because: "OTA take + orphan-night risk beating BAR pickup",
    clock: "Hold by 17:00 · arrivals day",
    decideBy: "17:00",
    seed: "hotel",
    status: "needs_you",
    autopilot: "stage",
    policy: {
      canAuto: ["Close last-room OTA allotment"],
      alwaysAsk: ["Post rate to public BAR", "Override group contract"],
      memoryLine: "Seen 6 similar Saturday pickups · auto-stage channel hold.",
      interruptReason: "Channel close is reversible — Needs you the first time today.",
    },
    futures: [
      { id: "leave", title: "Leave OTA open", euro: 0, note: "Distribution tax keeps leaking" },
      {
        id: "hold",
        title: "Hold allotment",
        euro: 410,
        note: "Protect BAR + stitch orphans",
        recommended: true,
      },
      { id: "dump", title: "Dump to OTA", euro: -180, note: "Fills rooms · destroys contribution" },
    ],
    recommendedFuture: "hold",
    actuators: [
      {
        system: "CHANNEL",
        title: "Close last-room allotment",
        detail: "Demo / policy — staged, not written to the CRS",
        policy: "auto",
      },
      {
        system: "REVENUE",
        title: "Offer BAR stitch on 3 orphan nights",
        detail: "Needs confirm",
        policy: "ask",
      },
    ],
  },
  {
    id: "d-8802",
    displayId: "D-8802",
    title: "CHARGE NO-SHOW DEPOSIT",
    sub: "Deposit authorized · not charged · Recover before night audit",
    wedge: "RECOVER",
    euro: 280,
    grade: "Expected",
    because: "Contracted recovery not executed — card on file, policy clear",
    clock: "Before night audit",
    seed: "hotel",
    status: "needs_you",
    autopilot: "suggest",
    policy: {
      canAuto: [],
      alwaysAsk: ["Charge guest card", "Post folio to PMS"],
      memoryLine: "Always-ask: guest charge is hospitality + books.",
      interruptReason: "Money movement on a guest folio — Needs you.",
    },
    futures: [
      { id: "waive", title: "Waive", euro: 0, note: "Hospitality choice · not recovery" },
      {
        id: "charge",
        title: "Charge deposit",
        euro: 280,
        note: "Recover contracted no-show",
        recommended: true,
        recover: true,
      },
    ],
    recommendedFuture: "charge",
    actuators: [
      {
        system: "PMS",
        title: "Prepare no-show charge",
        detail: "Confirm prepare — do not write to PMS/Stripe until you say so",
        policy: "ask",
      },
    ],
    lineage: "€ Verified only when the charge settles on the folio / processor.",
  },
  {
    id: "d-1842",
    displayId: "D-1842",
    title: "TUNA TATAKI SHORTFALL",
    sub: "Peak contribution protected · POS close",
    wedge: "SELL",
    euro: 1590,
    grade: "Verified",
    because: "Peak contribution protected · POS close",
    clock: "Sealed",
    seed: "service",
    status: "verified",
    autopilot: "verified",
    policy: {
      canAuto: [],
      alwaysAsk: [],
      memoryLine: "Trace sealed · not a live Decision.",
      interruptReason: null,
    },
    futures: [],
    recommendedFuture: "",
    actuators: [],
    lineage: "POS close + stock adjustment matched · Trace sealed",
  },
];

export const CATALOG: CatalogModule[] = [
  {
    id: "mod_peak",
    category: "SELL",
    decisionId: "d-1911",
    displayId: "D-1911",
    title: "WAIT 12 MINUTES",
    euro: 620,
    euroLabel: "Expected contribution",
    grade: "Expected",
    because: "Kitchen 92% · seat-now burns 9 second turns",
    clock: "Decide by 18:53 · ~11m",
    blurb: "38 inbound + delivery +31% — hold walk-ins, throttle delivery.",
    href: "/app/lab/control-center?seed=service&focus=d-1911",
    pinDefault: ["gm"],
  },
  {
    id: "mod_labor",
    category: "LABOR",
    decisionId: "d-1920",
    displayId: "D-1920",
    title: "HOLD LABOR PLAN",
    euro: 410,
    euroLabel: "Expected protected",
    grade: "Expected",
    because: "Headcount in plan — risk is kitchen mix, not roster",
    clock: "Tonight service",
    blurb: "Do not add labor; protect contribution via Wait-12 path.",
    href: "/app/lab/decisions/d-1920",
    pinDefault: ["gm"],
  },
  {
    id: "mod_menu",
    category: "SELL",
    decisionId: "d-7110",
    displayId: "D-7110",
    title: "DE-EMPHASIZE PEAK WINDOW",
    euro: 610,
    euroLabel: "Expected protected",
    grade: "Expected",
    because: "Signature mix burns cold-station minutes at peak",
    clock: "Tonight · 19:00–20:30",
    blurb: "BUY × LABOR × SELL — feature swap before rush-order.",
    href: "/app/lab/decisions/d-7110",
    pinDefault: ["gm"],
  },
  {
    id: "mod_supplier",
    category: "RECOVER",
    decisionId: "d-4102",
    displayId: "D-4102",
    title: "DISPUTE AP CREDIT",
    euro: 273,
    euroLabel: "Expected recovered",
    grade: "Expected",
    because: "INV-88421 above contract — CM draft pending",
    clock: "11 days · 28 Sep",
    blurb: "Chase credit before pay run. Verified only when the memo applies.",
    href: "/app/lab/control-center?seed=recover&focus=d-4102",
    pinDefault: ["cfo", "clevel"],
  },
  {
    id: "mod_buy_oil",
    category: "BUY",
    decisionId: "d-4102",
    displayId: "D-4102",
    title: "HOLD ABOVE-CONTRACT PO",
    euro: 273,
    euroLabel: "Expected avoided",
    grade: "Expected",
    because: "Next PO fires the same variance if yield unchecked",
    clock: "This week",
    blurb: "BUY detect that routes into RECOVER — do not reprice the menu.",
    href: "/app/lab/control-center?seed=recover&focus=d-4102",
    pinDefault: ["cfo"],
  },
  {
    id: "mod_hotel_ota",
    category: "SELL",
    decisionId: "d-8801",
    displayId: "D-8801",
    title: "HOLD OTA ALLOTMENT",
    euro: 410,
    euroLabel: "Expected contribution",
    grade: "Expected",
    because: "OTA take + orphan-night risk beating BAR pickup",
    clock: "Hold by 17:00",
    blurb: "Close last-room channel · stitch 3 orphan nights.",
    href: "/app/lab/control-center?seed=hotel&focus=d-8801",
    pinDefault: ["gm"],
  },
  {
    id: "mod_hotel_ns",
    category: "RECOVER",
    decisionId: "d-8802",
    displayId: "D-8802",
    title: "CHARGE NO-SHOW DEPOSIT",
    euro: 280,
    euroLabel: "Expected recovered",
    grade: "Expected",
    because: "Deposit authorized · not charged",
    clock: "Before night audit",
    blurb: "Contracted recovery. Verified only when the charge settles.",
    href: "/app/lab/control-center?seed=hotel&focus=d-8802",
    pinDefault: ["cfo"],
  },
  {
    id: "mod_tuna_v",
    category: "VALUE",
    decisionId: "d-1842",
    displayId: "D-1842",
    title: "TUNA TATAKI SHORTFALL",
    euro: 1590,
    euroLabel: "Verified protected",
    grade: "Verified",
    because: "Peak contribution protected · POS close + stock matched",
    clock: "Trace sealed",
    blurb: "The only Verified sell-side euro in this demo — lineage on the ledger.",
    href: "/app/lab/value?band=verified",
    pinDefault: ["cfo", "clevel"],
  },
  {
    id: "mod_value_ladder",
    category: "VALUE",
    title: "VERIFIED LADDER",
    euro: 2830,
    euroLabel: "Verified Value",
    grade: "Verified",
    because: "Ledger-matched · Trace sealed",
    clock: "Open ledger",
    blurb: "Identified → Expected → Observed → Attributed → Verified.",
    href: "/app/lab/value?band=verified",
    pinDefault: ["cfo", "clevel"],
  },
  {
    id: "mod_memory",
    category: "MEMORY",
    title: "FRIDAY PEAK CAPACITY",
    euro: 0,
    euroLabel: "12 comparable services",
    grade: "Playbook",
    because: "Feature-swap-first beat rush-order on 3 verified nights",
    clock: "Playbook v3",
    blurb: "What we tried → observed → verified → next Friday.",
    href: "/app/lab/memory?scope=playbook",
    pinDefault: ["gm"],
  },
];

const FOH: BriefPacket = {
  packet: "foh",
  title: "FOH packet",
  horizon: "Next 90m",
  lead: "Who’s coming · what to hold · tables linked to Decisions.",
  items: [
    {
      id: "f1",
      check: "Walk-in hold",
      detail: "Hold 2 walk-ins until 18:54 resume",
      because: "Wait-12 Decision open — seating now burns turns",
      when: "Until 18:54",
      euro: 620,
      grade: "Expected",
      displayId: "D-1911",
      decisionId: "d-1911",
      seed: "service",
      status: "do",
    },
    {
      id: "f2",
      check: "Turn-risk tables",
      detail: "T4 · T7 · T11 second-turn exposure",
      because: "Linked to D-1911 · delay seating until kitchen cools",
      when: "~11m",
      displayId: "D-1911",
      decisionId: "d-1911",
      seed: "service",
      status: "watch",
    },
    {
      id: "f3",
      check: "VIP / allergy",
      detail: "VIP party 6 · T12 nut allergy · must sit 18:50",
      because: "Operator context already on Decision — honor clock",
      when: "18:50",
      status: "do",
    },
    {
      id: "f4",
      check: "Arriving / returning",
      detail: "4 arrivals next 20m · 2 returning regulars",
      because: "Density compresses — hold walk-ins first",
      when: "18:42–19:00",
      status: "watch",
    },
  ],
};

const CHEF: BriefPacket = {
  packet: "chef",
  title: "Chef packet",
  horizon: "Next 90m",
  lead: "Ticket risk + feature path — not a full board.",
  items: [
    {
      id: "c1",
      check: "Cold-station load",
      detail: "Peak signature burning minutes 19:00–20:30",
      because: "De-emphasize peak window protects kitchen minutes",
      when: "Now",
      euro: 610,
      grade: "Expected",
      decisionId: "d-7110",
      displayId: "D-7110",
      status: "do",
    },
    {
      id: "c2",
      check: "Wait-12 implication",
      detail: "Hold walk-ins · throttle delivery 25m",
      because: "Seat-now →97% kitchen · 9 turns exposed",
      when: "Decide by 18:53",
      euro: 620,
      grade: "Expected",
      decisionId: "d-1911",
      displayId: "D-1911",
      seed: "service",
      status: "do",
    },
    {
      id: "c3",
      check: "Allergy / VIP tickets",
      detail: "T12 nut allergy · VIP 6 at 18:50 must sit",
      because: "Ticket flags already staged — confirm fire order",
      when: "18:50",
      status: "watch",
    },
    {
      id: "c4",
      check: "Feature high €/min",
      detail: "Push high-contribution plates while holding",
      because: "Protects contribution without rush-order chaos",
      when: "Tonight",
      status: "do",
    },
  ],
};

const GM_BRIEF: BriefPacket = {
  packet: "gm",
  title: "GM packet",
  horizon: "Tonight",
  lead: "Money decision + clock + Pulse — Approve when ready.",
  items: [
    {
      id: "g1",
      check: "Approve Wait-12",
      detail: "€620 Expected · decide by 18:53",
      because: "Protects second turns vs seat-now kitchen spike",
      when: "11m",
      euro: 620,
      grade: "Expected",
      decisionId: "d-1911",
      displayId: "D-1911",
      seed: "service",
      status: "do",
    },
    {
      id: "g2",
      check: "Pulse snapshot",
      detail: "Delivery tax + cancels watching · net €1,840 Expected",
      because: "Turbulence points map to open Decisions — not vanity KPIs",
      when: "Live",
      status: "watch",
    },
    {
      id: "g3",
      check: "Labor hold",
      detail: "Do not add headcount — mix risk, not roster",
      because: "D-1920 · €410 Expected protected",
      when: "Tonight",
      euro: 410,
      grade: "Expected",
      decisionId: "d-1920",
      displayId: "D-1920",
      status: "done",
    },
  ],
};

const CFO_BRIEF: BriefPacket = {
  packet: "cfo",
  title: "CFO packet",
  horizon: "14d · money & risk",
  lead: "Recover + Buy exposures — not the floor map.",
  items: [
    {
      id: "cf1",
      check: "Dispute AP credit",
      detail: "INV-88421 · €273 Expected · 11 days",
      because: "Contract €6.80/L vs invoice €7.45/L · CM draft pending",
      when: "28 Sep",
      euro: 273,
      grade: "Expected",
      decisionId: "d-4102",
      displayId: "D-4102",
      seed: "recover",
      status: "do",
    },
    {
      id: "cf2",
      check: "Hold above-contract PO",
      detail: "Block next oil PO until yield + CM path",
      because: "Same variance compounds if PO fires",
      when: "This week",
      euro: 273,
      grade: "Expected",
      decisionId: "d-4102",
      displayId: "D-4102",
      seed: "recover",
      status: "do",
    },
    {
      id: "cf3",
      check: "Verified ladder",
      detail: "€2,830 Verified · Trace sealed on tuna shortfall",
      because: "POS close + stock adjustment matched",
      when: "Since last check",
      euro: 2830,
      grade: "Verified",
      displayId: "D-1842",
      status: "done",
    },
  ],
};

const SERVICE_BRIEF: ServiceBrief = {
  phase: "mid",
  phaseLabel: "Mid-service · +42m",
  deltaNote: "Since pre-shift: kitchen +18pts · inbound +12 · Wait-12 still open",
  packets: { chef: CHEF, foh: FOH, gm: GM_BRIEF, cfo: CFO_BRIEF },
};

const HOTEL_BRIEF: ServiceBrief = {
  phase: "mid",
  phaseLabel: "Arrivals · +2h10m",
  deltaNote: "Since 14:00: OTA mix +9pts · 3 orphan nights · 1 no-show uncharged",
  packets: {
    chef: {
      packet: "chef",
      title: "Kitchen / F&B packet",
      horizon: "Next 90m",
      lead: "In-house dining load — not the room map.",
      items: [
        {
          id: "hc1",
          check: "In-house covers",
          detail: "Breakfast leftover + 18 in-house dinners inbound",
          because: "Occupancy 81% · don’t over-prep for OTA no-shows",
          when: "Tonight",
          status: "watch",
        },
        {
          id: "hc2",
          check: "VIP amenity",
          detail: "Suite 412 allergy — no nuts on turndown",
          because: "Already on the guest profile",
          when: "17:30",
          status: "do",
        },
      ],
    },
    foh: {
      packet: "foh",
      title: "Front desk packet",
      horizon: "Next 90m",
      lead: "Who’s arriving · what to hold · rooms linked to Decisions.",
      items: [
        {
          id: "hf1",
          check: "Arrivals",
          detail: "6 inbound before 18:00 · 2 late",
          because: "Density at desk — don’t release last-room OTA",
          when: "Until 18:00",
          status: "do",
        },
        {
          id: "hf2",
          check: "Orphan nights",
          detail: "412 · 418 · 221 disconnected Thu–Sat",
          because: "Linked to D-8801 · offer BAR stitch",
          when: "Hold by 17:00",
          euro: 360,
          grade: "Expected",
          displayId: "D-8801",
          decisionId: "d-8801",
          seed: "hotel",
          status: "do",
        },
        {
          id: "hf3",
          check: "No-show",
          detail: "Name on 308 · deposit authorized",
          because: "Recover path D-8802 — do not waive silently",
          when: "Night audit",
          euro: 280,
          grade: "Expected",
          displayId: "D-8802",
          decisionId: "d-8802",
          seed: "hotel",
          status: "watch",
        },
      ],
    },
    gm: {
      packet: "gm",
      title: "GM packet",
      horizon: "Arrivals day",
      lead: "Channel hold + Recover clock — hospitality first.",
      items: [
        {
          id: "hg1",
          check: "Hold OTA",
          detail: "€410 Expected · close last-room by 17:00",
          because: "Distribution tax beating BAR pickup",
          when: "17:00",
          euro: 410,
          grade: "Expected",
          displayId: "D-8801",
          decisionId: "d-8801",
          seed: "hotel",
          status: "do",
        },
        {
          id: "hg2",
          check: "No-show Recover",
          detail: "Charge vs waive is hospitality — decide once",
          because: "€280 Expected until the folio settles",
          when: "Night audit",
          euro: 280,
          grade: "Expected",
          displayId: "D-8802",
          seed: "hotel",
          status: "watch",
        },
      ],
    },
    cfo: {
      packet: "cfo",
      title: "CFO packet",
      horizon: "Pickup · 7d",
      lead: "In / out / forecast — Recover is the leak, not occupancy vanity.",
      items: [
        {
          id: "hcf1",
          check: "OTA tax",
          detail: "€1,250 out on remaining allotment",
          because: "Channel mix, not demand — D-8801 is the lever",
          when: "Today",
          euro: 1250,
          grade: "Expected",
          status: "watch",
        },
        {
          id: "hcf2",
          check: "No-show deposit",
          detail: "Authorized · not charged",
          because: "Verified only when processor settles",
          when: "Night audit",
          euro: 280,
          grade: "Expected",
          displayId: "D-8802",
          status: "do",
        },
      ],
    },
  },
};

const RECOVER_BRIEF: ServiceBrief = {
  phase: "pre",
  phaseLabel: "Monday morning · recover focus",
  deltaNote: "AP variance aged 11d · credit memo still draft · next PO at risk",
  packets: {
    chef: SERVICE_BRIEF.packets.chef,
    foh: SERVICE_BRIEF.packets.foh,
    gm: {
      ...SERVICE_BRIEF.packets.gm,
      lead: "Recover clock shares attention with tonight — don’t lose the AP path.",
      items: [
        {
          id: "g_r1",
          check: "AP dispute staged?",
          detail: "D-4102 · Confirm prepare if not yet staged",
          because: "€273 Expected until CM posts",
          when: "11d",
          euro: 273,
          grade: "Expected",
          seed: "recover",
          decisionId: "d-4102",
          displayId: "D-4102",
          status: "do",
        },
        ...SERVICE_BRIEF.packets.gm.items.slice(0, 2),
      ],
    },
    cfo: SERVICE_BRIEF.packets.cfo,
  },
};

export const VALUE_LADDER: ValueEntry[] = [
  {
    id: "v-id",
    displayId: "MAP",
    title: "Material money themes spotted across systems",
    money: {
      euro: 1503,
      grade: "Expected",
      because: "Identified is a watchlist — not cash",
    },
    stage: "identified",
  },
  {
    id: "v-ex",
    displayId: "MODEL",
    title: "Modeled if Decision path holds — not cash",
    money: {
      euro: 1061,
      grade: "Expected",
      because: "Open Decisions still deciding",
    },
    stage: "expected",
  },
  {
    id: "v-ob",
    displayId: "CLOSE",
    title: "Service / period closed · numbers landed",
    money: {
      euro: 1840,
      grade: "Observed",
      because: "Tonight’s net is Observed only after close — still not Verified",
    },
    stage: "observed",
  },
  {
    id: "v-at",
    displayId: "LINK",
    title: "Linked to Decision + prepared action",
    money: {
      euro: 610,
      grade: "Expected",
      because: "Peak de-emphasis · STRONGLY_ATTRIBUTED · DEMO — not Verified campaign revenue",
      demo: true,
    },
    stage: "attributed",
  },
  {
    id: "v-vf",
    displayId: "D-1842",
    title: "Tuna Tataki shortfall before peak",
    money: {
      euro: 1590,
      grade: "Verified",
      because: "Peak contribution protected · POS close",
      lineage: "POS close + stock adjustment matched · Trace sealed",
    },
    stage: "verified",
  },
  {
    id: "v-vf2",
    displayId: "LEDGER",
    title: "Verified Value",
    money: {
      euro: 2830,
      grade: "Verified",
      because: "Trace sealed · book-matchable",
      lineage: "D-1842 tuna shortfall + prior closes matched on ledger",
    },
    stage: "verified",
  },
];

export const VALUE_ROWS: ValueEntry[] = [
  {
    id: "d-1842",
    displayId: "D-1842",
    title: "Tuna Tataki shortfall before peak",
    money: {
      euro: 1590,
      grade: "Verified",
      because: "Peak contribution protected · POS close",
      lineage: "POS close + stock adjustment matched · Trace sealed",
    },
    stage: "verified",
  },
  {
    id: "d-7110v",
    displayId: "D-7110",
    title: "DE-EMPHASIZE 19:00–20:30 ONLY",
    money: {
      euro: 610,
      grade: "Expected",
      because: "Peak de-emphasis · STRONGLY_ATTRIBUTED · DEMO",
      demo: true,
    },
    stage: "attributed",
  },
  {
    id: "d-7302",
    displayId: "D-7302",
    title: "PROTECT STOCK · SHIFT PROMOTION",
    money: {
      euro: 280,
      grade: "Expected",
      because: "Stock protected · MODELED attribution · DEMO SIGNAL — not verified campaign revenue",
      demo: true,
    },
    stage: "expected",
  },
  {
    id: "d-7401",
    displayId: "D-7401",
    title: "FIX KITCHEN MIX",
    money: {
      euro: 350,
      grade: "Expected",
      because: "Kitchen-mix intervention · STRONGLY_ATTRIBUTED · DEMO",
      demo: true,
    },
    stage: "attributed",
  },
];

export const MEMORY_STORIES: MemoryStory[] = [
  {
    id: "friday-peak",
    title: "Friday peak capacity",
    euro: 620,
    grade: "Expected",
    tried: "Feature-swap-first vs rush-order across matching Fridays",
    observed: "Kitchen minutes recovered when signature mix de-emphasized",
    verified: "3 nights Verified contribution protected vs seat-now baseline",
    nextTime: "Default Wait-12 + feature path before adding labor",
    links: [
      {
        label: "D-7110 BUY × LABOR × SELL · peak signature",
        because: "Cold-station minutes burn at peak",
        href: "/app/lab/decisions/d-7110",
      },
      {
        label: "D-1911 Wait-12 path · Friday capacity",
        because: "Kitchen constraint before seats",
        href: "/app/lab/control-center?seed=service&focus=d-1911",
      },
      {
        label: "BRIEF Open FOH / Chef packet",
        because: "Protocol beats dashboard dump",
        href: "/app/lab/service?packet=foh",
      },
    ],
  },
  {
    id: "ap-credits",
    title: "AP credit before pay run",
    euro: 273,
    grade: "Expected",
    tried: "Draft credit request + hold above-contract PO (never auto-remit)",
    observed: "Variance sits on statement until CM applies — Expected stays Expected",
    verified: "Not Verified in this demo. Gold path = credit_memo.applied to invoice.",
    nextTime: "Surface before next pay run · escalate if aging > 60d",
    links: [
      {
        label: "D-4102 Dispute AP credit",
        because: "INV-88421 above contract — CM draft pending",
        href: "/app/lab/control-center?seed=recover&focus=d-4102",
      },
    ],
  },
];

export const HEALTH: HealthSource[] = [
  {
    id: "pos",
    name: "POS",
    status: "ok",
    freshness: "40s ago",
  },
  {
    id: "reservations",
    name: "Reservations",
    status: "ok",
    freshness: "2m ago",
  },
  {
    id: "kds",
    name: "KDS",
    status: "ok",
    freshness: "40s ago",
  },
  {
    id: "delivery",
    name: "Delivery",
    status: "degraded",
    freshness: "4m ago",
    impact: "Affects D-1911 forecast confidence",
  },
  {
    id: "ap",
    name: "AP ledger",
    status: "stale",
    freshness: "18h ago",
    impact: "D-4102 aging clock still trusted from last statement",
  },
];

export function getDecision(id: string): LabDecision | undefined {
  const key = id.toLowerCase();
  return DECISIONS.find((d) => d.id === key || d.displayId.toLowerCase() === key);
}

export function decisionsForSeed(seed: LabSeed): LabDecision[] {
  if (seed === "hotel") {
    return DECISIONS.filter((d) => d.seed === "hotel" || d.id === "d-1842");
  }
  if (seed === "recover") {
    return DECISIONS.filter((d) =>
      ["d-4102", "d-1911", "d-1920", "d-7110", "d-1842"].includes(d.id),
    );
  }
  return DECISIONS.filter((d) => d.seed !== "hotel");
}

export function worldFor(seed: LabSeed): LabWorld {
  const decisions = decisionsForSeed(seed);
  if (seed === "hotel") {
    return {
      seed,
      industry: "hotel",
      location: "Northstar · Berlin Mitte Hotel",
      serviceLabel: "Arrivals day",
      nowLabel: "16:10",
      liveNote: "Pickup live",
      pulse: HOTEL_PULSE,
      heroDecisionId: "d-8801",
      decisions,
      floor: [
        { id: "a", label: "Arriving", value: "6 rooms · 90m", because: "Desk density — hold last-room OTA first" },
        { id: "r", label: "Returning", value: "2 loyalty", because: "Honor upgrades after channel hold" },
        { id: "v", label: "VIP / allergy", value: "Suite 412 nut", because: "Must ready 17:30 — already on Decision" },
        { id: "o", label: "Orphan risk", value: "412 · 418 · 221", because: "Linked to D-8801 · €410 Expected" },
      ],
      winLoss: [
        {
          id: "w",
          side: "win",
          title: "Where we protected",
          money: {
            euro: 2830,
            grade: "Verified",
            because: "Prior restaurant close matched on ledger — not hotel math",
            lineage: "D-1842 tuna shortfall + prior closes",
          },
          href: "/app/lab/value?band=verified",
        },
        {
          id: "l",
          side: "loss",
          title: "Where we leak",
          money: {
            euro: 280,
            grade: "Expected",
            because: "No-show deposit authorized — not charged",
          },
          href: "/app/lab/control-center?seed=hotel&focus=d-8802",
        },
      ],
      themes: [
        {
          id: "t1",
          title: "Channel mix taxing pickup",
          wedge: "SELL × BUY",
          money: {
            euro: 410,
            grade: "Expected",
            because: "OTA last-room still open — Wait-hold is the Decision",
          },
          href: "/app/lab/control-center?seed=hotel&focus=d-8801",
        },
        {
          id: "t2",
          title: "Contracted recovery idle",
          wedge: "RECOVER",
          money: {
            euro: 280,
            grade: "Expected",
            because: "No-show deposit authorized, not executed",
          },
          href: "/app/lab/control-center?seed=hotel&focus=d-8802",
        },
        {
          id: "t3",
          title: "Verified protection banked",
          wedge: "VALUE",
          money: {
            euro: 2830,
            grade: "Verified",
            because: "Ledger-matched tuna shortfall + prior closes",
            lineage: "Trace sealed",
          },
          href: "/app/lab/value?band=verified",
        },
      ],
      brief: HOTEL_BRIEF,
      verifiedBank: {
        euro: 2830,
        grade: "Verified",
        because: "Ledger-matched · Trace sealed",
        lineage: "D-1842 tuna shortfall + prior closes matched on ledger",
      },
      activeExposure: {
        euro: 690,
        grade: "Expected",
        because: "Open hotel Decisions still deciding",
      },
    };
  }

  if (seed === "recover") {
    return {
      seed,
      industry: "restaurant",
      location: "Northstar · Berlin Mitte",
      serviceLabel: "Monday morning",
      nowLabel: "09:12",
      liveNote: "Recover clock",
      pulse: RECOVER_PULSE,
      heroDecisionId: "d-4102",
      decisions,
      floor: [
        { id: "inv", label: "Invoice", value: "INV-88421 Bluefin", because: "€7.45/L · 420 L vs contract €6.80/L" },
        { id: "cm", label: "Credit memo", value: "CM-DRAFT", because: "Not posted — Expected until applied" },
        { id: "po", label: "Next PO", value: "Hold", because: "Same variance compounds if it fires" },
      ],
      winLoss: [
        {
          id: "w",
          side: "win",
          title: "Where we protected",
          money: {
            euro: 2830,
            grade: "Verified",
            because: "tuna shortfall + prior closes matched on ledger",
            lineage: "Trace sealed · book-matchable",
          },
          href: "/app/lab/value?band=verified",
        },
        {
          id: "l",
          side: "loss",
          title: "Where we leak",
          money: {
            euro: 273,
            grade: "Expected",
            because: "INV-88421 above contract — CM not posted",
          },
          href: "/app/lab/control-center?seed=recover&focus=d-4102",
        },
      ],
      themes: [
        {
          id: "t1",
          title: "Peak contribution at risk",
          wedge: "SELL × LABOR",
          money: {
            euro: 620,
            grade: "Expected",
            because: "Kitchen constraint before seats — Wait-12 still open",
          },
          href: "/app/lab/control-center?seed=service",
        },
        {
          id: "t2",
          title: "AP leakage open",
          wedge: "RECOVER × BUY",
          money: {
            euro: 273,
            grade: "Expected",
            because: "Invoice above contract · credit memo not posted",
          },
          href: "/app/lab/control-center?seed=recover",
        },
        {
          id: "t3",
          title: "Verified protection banked",
          wedge: "VALUE",
          money: {
            euro: 2830,
            grade: "Verified",
            because: "Ledger-matched tuna shortfall + prior closes",
            lineage: "Trace sealed",
          },
          href: "/app/lab/value?band=verified",
        },
      ],
      brief: RECOVER_BRIEF,
      verifiedBank: {
        euro: 2830,
        grade: "Verified",
        because: "Ledger-matched · Trace sealed",
        lineage: "D-1842 tuna shortfall + prior closes matched on ledger",
      },
      activeExposure: {
        euro: 1061,
        grade: "Expected",
        because: "Open Decisions still deciding",
      },
    };
  }

  return {
    seed,
    industry: "restaurant",
    location: "Northstar · Berlin Mitte",
    serviceLabel: "Dinner service",
    nowLabel: "18:42",
    liveNote: "Live turbulence",
    pulse: SERVICE_PULSE,
    heroDecisionId: "d-1911",
    decisions,
    floor: [
      { id: "arr", label: "Arriving", value: "4 covers · 20m", because: "density compresses — hold walk-ins first" },
      { id: "ret", label: "Returning", value: "2 regulars", because: "honor tables after Wait-12 resume 18:54" },
      { id: "vip", label: "VIP / allergy", value: "VIP 6 · T12 nut", because: "must sit 18:50 — already on Decision context" },
      { id: "turn", label: "Turn-risk", value: "T4 · T7 · T11", because: "linked to D-1911 · €620 Expected" },
    ],
    winLoss: [
      {
        id: "w",
        side: "win",
        title: "Where we protected",
        money: {
          euro: 2830,
          grade: "Verified",
          because: "tuna shortfall + prior closes matched on ledger",
          lineage: "Trace sealed · book-matchable",
        },
        href: "/app/lab/value?band=verified",
      },
      {
        id: "l",
        side: "loss",
        title: "Where we leak",
        money: {
          euro: 273,
          grade: "Expected",
          because: "INV-88421 above contract — CM not posted",
        },
        href: "/app/lab/control-center?seed=recover&focus=d-4102",
      },
    ],
    themes: [
      {
        id: "t1",
        title: "Peak contribution at risk",
        wedge: "SELL × LABOR",
        money: {
          euro: 620,
          grade: "Expected",
          because: "Kitchen constraint before seats — Wait-12 still open",
        },
        href: "/app/lab/control-center?seed=service",
      },
      {
        id: "t2",
        title: "AP leakage open",
        wedge: "RECOVER × BUY",
        money: {
          euro: 273,
          grade: "Expected",
          because: "Invoice above contract · credit memo not posted",
        },
        href: "/app/lab/control-center?seed=recover",
      },
      {
        id: "t3",
        title: "Verified protection banked",
        wedge: "VALUE",
        money: {
          euro: 2830,
          grade: "Verified",
          because: "Ledger-matched tuna shortfall + prior closes",
          lineage: "Trace sealed",
        },
        href: "/app/lab/value?band=verified",
      },
    ],
    brief: SERVICE_BRIEF,
    verifiedBank: {
      euro: 2830,
      grade: "Verified",
      because: "Ledger-matched · Trace sealed",
      lineage: "D-1842 tuna shortfall + prior closes matched on ledger",
    },
    activeExposure: {
      euro: 1061,
      grade: "Expected",
      because: "Open Decisions still deciding",
    },
  };
}

export const LAB_NAV = [
  { id: "center", label: "Center", href: "/app/lab/control-center" },
  { id: "decisions", label: "Decisions", href: "/app/lab/decisions" },
  { id: "catalog", label: "Catalog", href: "/app/lab/my-center" },
  { id: "value", label: "Value", href: "/app/lab/value?band=verified" },
  { id: "memory", label: "Memory", href: "/app/lab/memory?scope=playbook" },
] as const;
