/**
 * Berlin Mitte - hospitality / allergy demo fixtures.
 * Synthetic · explicit sources only · no inferred allergies.
 */

import { countContainment } from "./menuAllergens";
import type {
  AllergyAlert,
  DietaryNote,
  ServiceMoment,
  ServiceRequirement,
} from "./types";

const peanutCounts = countContainment("peanut");
const shellfishCounts = countContainment("shellfish");

export const DEMO_SERVICE_MOMENTS: ServiceMoment[] = [
  {
    id: "sm_bday_12",
    reservationId: "r_sophie",
    tableLabel: "Table 12",
    time: "19:30",
    partySize: 4,
    kind: "birthday",
    label: "Birthday",
    guestLabel: "Sophie Laurent party",
    priority: "RECOGNIZE",
  },
  {
    id: "sm_eng_9",
    reservationId: "r_engagement",
    tableLabel: "Table 9",
    time: "20:15",
    partySize: 2,
    kind: "engagement",
    label: "Engagement",
    guestLabel: null,
    priority: "RECOGNIZE",
  },
  {
    id: "sm_ann_18",
    reservationId: "r_anniv",
    tableLabel: "Table 18",
    time: "20:00",
    partySize: 2,
    kind: "anniversary",
    label: "Anniversary",
    guestLabel: null,
    priority: "RECOGNIZE",
  },
  {
    id: "sm_bday_7",
    reservationId: "r_bday7",
    tableLabel: "Table 7",
    time: "19:00",
    partySize: 6,
    kind: "birthday",
    label: "Birthday",
    guestLabel: null,
    priority: "RECOGNIZE",
  },
  {
    id: "sm_bday_14",
    reservationId: "r_bday14",
    tableLabel: "Table 14",
    time: "21:00",
    partySize: 3,
    kind: "birthday",
    label: "Birthday",
    guestLabel: null,
    priority: "RECOGNIZE",
  },
  {
    id: "sm_bday_3",
    reservationId: "r_bday3",
    tableLabel: "Table 3",
    time: "18:45",
    partySize: 4,
    kind: "birthday",
    label: "Birthday",
    guestLabel: null,
    priority: "RECOGNIZE",
  },
  {
    id: "sm_ret_21",
    reservationId: "r_daniel",
    tableLabel: "Table 21",
    time: "19:45",
    partySize: 4,
    kind: "returning",
    label: "Returning guest",
    guestLabel: "Daniel Weber",
    priority: "RECOGNIZE",
  },
];

export const DEMO_SERVICE_REQUIREMENTS: ServiceRequirement[] = [
  {
    id: "sr_quiet_12",
    reservationId: "r_sophie",
    tableLabel: "Table 12",
    time: "19:30",
    partySize: 4,
    kind: "quiet_table",
    label: "Quiet table",
    note: "Quiet seating requested on reservation",
    priority: "PREPARE",
  },
  {
    id: "sr_quiet_9",
    reservationId: "r_engagement",
    tableLabel: "Table 9",
    time: "20:15",
    partySize: 2,
    kind: "quiet_table",
    label: "Quiet table",
    note: "Engagement · prefer quieter section - do not aggressively turn",
    priority: "PREPARE",
  },
  {
    id: "sr_terr_1",
    reservationId: "r_terr1",
    tableLabel: "T1",
    time: "19:00",
    partySize: 4,
    kind: "terrace",
    label: "Terrace",
    note: "Terrace requested",
    priority: "PREPARE",
  },
  {
    id: "sr_terr_2",
    reservationId: "r_terr2",
    tableLabel: "T4",
    time: "19:30",
    partySize: 2,
    kind: "terrace",
    label: "Terrace",
    note: "Terrace requested",
    priority: "PREPARE",
  },
  {
    id: "sr_terr_3",
    reservationId: "r_terr3",
    tableLabel: "T6",
    time: "20:00",
    partySize: 3,
    kind: "terrace",
    label: "Terrace",
    note: "Terrace requested",
    priority: "PREPARE",
  },
  {
    id: "sr_private",
    reservationId: "r_private",
    tableLabel: "Private",
    time: "19:15",
    partySize: 10,
    kind: "private_dining",
    label: "Private dining setup",
    note: "Private room · AV + tasting setup by 18:45",
    priority: "PREPARE",
  },
];

export const DEMO_ALLERGY_ALERTS: AllergyAlert[] = [
  {
    id: "al_peanut_12",
    reservationId: "r_sophie",
    tableLabel: "Table 12",
    time: "19:30",
    partySize: 4,
    guestOfParty: "1 of 4",
    guestLabel: "Sophie Laurent party",
    allergen: "peanut",
    allergenLabel: "Peanut",
    severityExplicit: "severe",
    status: "CONFIRMED",
    needsClarification: false,
    clarificationHint: null,
    fohInstruction: "Confirm allergy on arrival before ordering.",
    kitchenInstruction:
      "Avoid peanut-containing dishes and follow restaurant cross-contact procedure.",
    source: {
      system: "OpenTable",
      field: "reservation_note",
      originalText:
        "My wife has a severe peanut allergy and we're celebrating her birthday. Quiet table if possible.",
      recordedAt: "2026-08-18T14:22:00+02:00",
    },
    fromPriorVisit: false,
    menuContainsCount: peanutCounts.contains,
    menuCrossContactCount: peanutCounts.crossContact,
    fohAcknowledged: true,
    kitchenAcknowledged: true,
    priority: "CRITICAL",
  },
  {
    id: "al_shell_18",
    reservationId: "r_anniv",
    tableLabel: "Table 18",
    time: "20:00",
    partySize: 2,
    guestOfParty: "1 of 2",
    guestLabel: null,
    allergen: "shellfish",
    allergenLabel: "Shellfish",
    severityExplicit: "severe",
    status: "UNCONFIRMED",
    needsClarification: false,
    clarificationHint: null,
    fohInstruction: "Confirm with guest before ordering.",
    kitchenInstruction:
      "Shellfish exclusion · check shared fryer / seafood prep before plating.",
    source: {
      system: "OpenTable",
      field: "allergy_field",
      originalText: "Severe shellfish allergy.",
      recordedAt: "2026-08-17T09:10:00+02:00",
    },
    fromPriorVisit: false,
    menuContainsCount: shellfishCounts.contains,
    menuCrossContactCount: shellfishCounts.crossContact,
    fohAcknowledged: true,
    kitchenAcknowledged: false,
    priority: "CRITICAL",
  },
  {
    id: "al_ambig_5",
    reservationId: "r_ambig",
    tableLabel: "Table 5",
    time: "19:15",
    partySize: 3,
    guestOfParty: "party",
    guestLabel: null,
    allergen: "tree_nut",
    allergenLabel: "Nuts (unclear)",
    severityExplicit: null,
    status: "UNCONFIRMED",
    needsClarification: true,
    clarificationHint:
      'Guest wrote "No nuts please." Clarify whether allergy or preference before order.',
    fohInstruction: "Clarify: allergy or preference? Do not assume.",
    kitchenInstruction: "Hold nut-containing items until FOH clarifies.",
    source: {
      system: "OpenTable",
      field: "reservation_note",
      originalText: "No nuts please",
      recordedAt: "2026-08-19T10:02:00+02:00",
    },
    fromPriorVisit: false,
    menuContainsCount: peanutCounts.contains,
    menuCrossContactCount: peanutCounts.crossContact,
    fohAcknowledged: false,
    kitchenAcknowledged: false,
    priority: "CRITICAL",
  },
];

export const DEMO_DIETARY_NOTES: DietaryNote[] = [
  {
    id: "diet_gluten",
    reservationId: "r_gluten",
    tableLabel: "Table 11",
    time: "20:30",
    kind: "gluten_related",
    label: "Gluten-related dietary request",
    note: "Guest requested gluten-free options - preference / dietary, not recorded as allergy.",
    isAllergy: false,
  },
  {
    id: "diet_veg",
    reservationId: "r_veg",
    tableLabel: "Table 4",
    time: "19:00",
    kind: "vegetarian",
    label: "Vegetarian",
    note: "Vegetarian tasting requested",
    isAllergy: false,
  },
  {
    id: "diet_vegan",
    reservationId: "r_vegan",
    tableLabel: "Bar 2",
    time: "18:30",
    kind: "vegan",
    label: "Vegan",
    note: "Vegan preference",
    isAllergy: false,
  },
  {
    id: "diet_pref",
    reservationId: "r_pref",
    tableLabel: "Table 16",
    time: "21:15",
    kind: "preference",
    label: "No cilantro preference",
    note: "Dislikes cilantro - preference only",
    isAllergy: false,
  },
  {
    id: "diet_veg2",
    reservationId: "r_veg2",
    tableLabel: "Table 8",
    time: "19:45",
    kind: "vegetarian",
    label: "Vegetarian",
    note: "One vegetarian guest",
    isAllergy: false,
  },
];

export const DEMO_HOSPITALITY_AGG = {
  reservedCovers: 142,
  returningGuests: 42,
  birthdays: 4,
  engagements: 1,
  anniversaries: 1,
  terraceRequests: 3,
  quietTableRequests: 2,
  privateDiningSetups: 1,
  dietaryNotes: 5,
  /** Explicit allergy reservations (excludes ambiguous preference text). */
  allergyAlerts: 2,
  /** Kitchen-critical = severe explicit + kitchen not acknowledged */
  kitchenCritical: 1,
  serviceNotesNeedingAttention: 2,
} as const;
